### ISSUE TITLE
Can't connect with chrome to https://localhost

### ISSUE THREAD

**Issue by leobut** [esplo/docker-local-ssl-termination-proxy#3]
Command that I used to run the container:

```
docker run -it \
  -e "HOST_IP=`ipconfig getifaddr en0`" \
  -e "PORT=8000" \
  -p 443:443 \
  --rm \
  esplo/docker-local-ssl-termination-proxy
```

Error on Chrome:
<img width="626" alt="Screenshot 2021-07-20 at 16 22 18" src="https://user-images.githubusercontent.com/9163917/126360196-b981ba0d-6c42-4bcd-9536-8110bbe8a3cc.png">

Log (click the image to enlarge):
![Untitled](https://user-images.githubusercontent.com/9163917/126359889-57312bf1-b4be-49bd-961a-ae545d7c930b.png)

My local server runs on port 8000.
OSX 11.4
Docker Desktop 3.5.2
Engine: 20.10.7

**Comment by esplo** [comment]
Chrome changed its policy to hide the button to access on untrusted certificates. Check this SO post to bypass this. My recommendation is to type "thisisunsafe".
https://stackoverflow.com/questions/58802767/no-proceed-anyway-option-on-neterr-cert-invalid-in-chrome-on-macos
I'll update README for better guide.
